language: java
jdk: oraclejdk8
after_success: "./.travis.after_success.sh"
sudo: required
dist: trusty
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/com/vaadin/addon
script:
  - mvn -B -e -V clean install
env:
  global:
  - secure: KWHu7lGaBFY6DmiIwRH8uftetozH+GUgbAjrGno6ASzNzdZtyhqEac1OybnWvDHgKsFLjNHzlm0OeFb1QDOJQKH2U9pt2KFHsG8fEIYKDKFu8sARSmOy/dfYS5EDGIZdbyexE1RO4k6SCDXUcB18myAraSCUZAaojr8wIT7cdYZZNYCqbWYW6ZfM1OcMRMFL6RFJYoQSBzvvHzDwjY4tra0Aqcd5pt+laCIyuHZCLuamFe+2qjHishbSLrjBjsfNqI7WsEl0filG9ViioAhWkA7JBpzaJTegMkeiw22WAKl76BqgfKXsp31vcI6K8e/Uk4rWiRmb5YSWTyr8dsnV/Fwq1POTrWhzKXS8yY3QDyb6OE6ow7ffOhZjoXM+gMVMy93DnEjDX+EbJgKHho8B0EYi4Ys2BpJWerGUYe4JeATJFbyzDE9a7nskCYJwiyLUrSzYrrE7WMQFCrjDSoBxgRxuqiYdsvPkh9GBrtalab6bQcqG0x+eMYYmiVnHwoiUYraOEDxR3EgqGCSzEFobbtcu2l5/mIPVGz6o0r78FIYwmrYCss/9GIN9SVaHFv/y833RQGpyAA85smDZEveQ2z/6IFyHkpU0Xj6k9ndlM34r4QFmPUg7MvRihzMGr/8rlgOGOg+HRLojggMunOhHSE1IXJVccZUoTKdxS58qWZU=
  - secure: HotwKPpSotGyBsTNzdFf1WUhxDE/zSLGZfrPauzUxLIr33esRK4bDbCRX0wGgYvLfbK3CNcNZjxekWsi52zV4orNkCwglYIP02ekvrk+jVcFCgyV/3cnzX0aclR5jFF00psDcXbSpQ5LT41tYm8R1n0AkPlERXjHZ8w6dKfh1yxTkBQo+It8h7BVS+q+rcvwGu0GyEPPPPsD5dbshkaZ4Mc/NXx0eXsMGakaoTStwu91yHeTiEHspnbhIiOXVBD5DUn8vKQiFcjOskcOXfRfdbhJBxYXlj2qoOhYx4VCs7JN6nJac4dhLxDU/1pLjPQT6tXn5T6mSHKgBoCAi/P53q7Xba0VZ9KRVpXRxUYRzIJRltqDQVxuiQVmRBUJ2SMs+iXw3ucWt6QzjNa+aI0Ap3muCgPqNPIpFV0wqXtd0HNdoJK7/6G/gN4vWups3nOsEPlA1Ga+7h3CjNgs/m/8Wm7bTpfD2WhF4coKju2KdxduGD5XECpzyxfal74GJ4d1jXG/jQlhmhP7C3qWm3fNVljo4N+sp0iCxrNuhVKUyFXdsJwMqFF9NYANIxxn1cKvy5VPU8w03sT0d87C6/Ylerw3SRJLODgB8R2j9XFp6EZzdF+X8JD6fNcajSYxhAFmAMgvKJqfmf6KamFb/Mq/vzTsAtE3LOQhjkVUNqHRc1M=
